server:
  port: ${SPRING_PORT:8080}

spring:
  application:
    name: spring-boot-service
  
  # MongoDB Config
  data:
    mongodb:
      uri: ${SPRING_MONGO_URI:mongodb://localhost:27017/copilot_db}
    
    # Redis Cache Config
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  
  # RabbitMQ Broker Config
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 2
        max-concurrency: 5
        prefetch: 1
